### ISSUE TITLE
Crash after couple of minutes

### ISSUE THREAD

**Issue by loki-sft** [Bl4cksh4rk1990/ioBroker.siro#17]
Since a couple of days the adapter is crashing. I switched to debug mode and the log shows thats comming from the "Read Devices..." loop.

here is the dump:
`TypeError: Cannot read properties of undefined (reading '0') at 
Request._callback (/opt/iobroker/node_modules/iobroker.siro/main.js:200:30) at 
self.callback (/opt/iobroker/node_modules/request/request.js:185:22) at 
Request.emit (node:events:517:28) at 
Request.<anonymous> (/opt/iobroker/node_modules/request/request.js:1154:10) at 
Request.emit (node:events:517:28) at 
IncomingMessage.<anonymous> (/opt/iobroker/node_modules/request/request.js:1076:12) at 
Object.onceWrapper (node:events:631:28) at 
IncomingMessage.emit (node:events:529:35) at 
endReadableNT (node:internal/streams/readable:1400:12) at 
process.processTicksAndRejections (node:internal/process/task_queues:82:21)`

**Comment by Bl4cksh4rk1990** [comment]
I just checked the issue. Is it possible that your devices are not assigned to a room?

**Comment by loki-sft** [comment]
No, every device (6) are assigned in 3 rooms.  I added a few more debug lines to the loop. Here is the output:
`siro.0	2024-09-05 11:24:04.173	debug	Rollo Flur rechts
siro.0	2024-09-05 11:24:04.173	debug	Rollo Flur links
siro.0	2024-09-05 11:24:04.173	debug	Flur
siro.0	2024-09-05 11:24:04.173	debug	2
siro.0	2024-09-05 11:24:04.173	debug	Rollo Tino
siro.0	2024-09-05 11:24:04.173	debug	Tino
siro.0	2024-09-05 11:24:04.173	debug	1
siro.0	2024-09-05 11:24:04.172	debug	Rollo Garten rechts
siro.0	2024-09-05 11:24:04.172	debug	Rollo Garten links
siro.0	2024-09-05 11:24:04.172	debug	Rollo Hof
siro.0	2024-09-05 11:24:04.172	debug	Wohnzimmer
siro.0	2024-09-05 11:24:04.172	debug	0
siro.0	2024-09-05 11:24:04.172	debug	Read Devices...`

then it start over again a couple of times with "Read DEvices..." and the crash

**Comment by Bl4cksh4rk1990** [comment]
Ich denke mal wir können auf deutsch weiter schreiben. 
Ich konnte den Fehler gerade selbst nachstellen. Wenn ich den Fehler behoben habe, dann melde ich mich nochmal.

**Comment by loki-sft** [comment]
Oki doki, danke sehr.   ;)

**Comment by Bl4cksh4rk1990** [comment]
So ich habe jetzt eine Fehlerbehebung eingebaut.
Den neuen Adapter kannst du jetzt über Github installieren. Die Version lautet 1.0.13

**Comment by loki-sft** [comment]
Funktioniert! Der Fehler ist weg.
